{% set version = "1.9.12" %}

package:
  name: basictools-split
  version: {{ version }}


source:
  url: https://gitlab.com/DRTI/basic-tools/-/archive/{{ version }}/basic-tools-{{ version }}.tar.bz2
  sha256: a7b9ebb0df0a8a280e09e1393205d2bfdca382cad162cafadf646adbe0518c3a

build:
  number: 1
  skip: true  # [py==38 and osx]

requirements:
  host:
    - python

outputs:
  - name: basictools-core
    version: {{ version }}
    script: build_core.sh  # [not win]
    script: bld_core.bat  # [win]
    build:
      script_env:
        - BASICTOOLS_DISABLE_MKL=0
        - BASICTOOLS_USE_EIGENCYEIGEN=0
      entry_points:
        - "MeshFileConvert = BasicTools.IO.MeshFileConverter:Main"
      skip_compile_pyc: "BasicToolsParaViewBridge.py"

    requirements:
      build:
        - python
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - cython <3
      host:
        - python
        - numpy
        - cython <3
        - sympy
        - eigency
        - mkl
        - mkl-include
        - setuptools
        - setuptools-scm
        - eigen
        - libboost-headers
        - pip
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.9
        - sympy
        - eigency
        - mkl
        - networkx >=3.0
        - scikit-sparse
    test:
      imports:
        - BasicTools
      commands:
        - python -u -m BasicTools.Helpers.Tests

  - name: basictools-extensions
    version: {{ version }}
    requirements:
      host:
        - python
        - numpy
        - vtk
        - psutil
        - scikit-sparse
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - vtk
        - psutil
        - scikit-sparse
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
    test:
      imports:
        - psutil
        - sksparse.cholmod
        - h5py
        - meshio
        - networkx

  - name: basictools
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage('basictools-core', max_pin='x.x.x') }}
        - {{ pin_subpackage('basictools-extensions', max_pin='x.x.x') }}
    test:
      imports:
        - BasicTools
      commands:
        - python -u -m BasicTools.Helpers.Tests

  - name: basictools-devenv
    version: {{ version }}
    requirements:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - python
      - {{ pin_compatible('numpy') }}
      - sympy
      - cython <3
      - eigency
      - mkl
      - mkl-include
      - setuptools-scm
      - eigen
      - scipy >=1.9
      - eigency
      - scikit-sparse
      - h5py
      - pycgns
      - networkx >=3.0
      - libboost-headers
      - pytest
      - vtk
    test:
      imports:
        - numpy

about:
  home: https://gitlab.com/DRTI/basic-tools
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Tools for finite element computations

extra:
  recipe-maintainers:
    - fbordeu
